#! /bin/bash

asg_ssh () {
    aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $@ | jq ".AutoScalingGroups[].Instances | .[].InstanceId" | xargs -I % echo '%.ln' | xargs -I % tmux split-window "tmux select-layout tiled && ssh -oStrictHostKeyChecking=no %"
}
asg_list () {
    aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $@ | jq ".AutoScalingGroups[].Instances | .[].InstanceId"
}
